#Adapted from equinox/mkdocs.yaml
theme:
    name: material
    custom_dir: docs/overrides
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: material/eqxvision  # Eqxvision logo in top left
    favicon: "_static/favicon.png"

site_name: Eqxvision
site_description: The documentation for Eqxvision, a vision package built on Equinox.
site_author: Contributing Authors
site_url:

repo_url: https://github.com/paganpasta/eqxvision
repo_name: paganpasta/eqxvision
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

strict: true  # Don't allow warnings during the build process

extra_javascript:
    # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - _static/custom_css.css

markdown_extensions:
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
          custom_icons:
            - docs/overrides/.icons
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - admonition
    - toc:
        permalink: "#"  # Adds a clickable permalink to each section heading
        toc_depth: 4
    - tables

plugins:

    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - include_exclude_files:
        include:
            - ".htaccess"
        exclude:
            - "_overrides"
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks
                    - pytkdocs_tweaks.main()

                selection:
                    inherited_members: true  # Allow looking up inherited methods
                rendering:
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display "diffrax.asdf" not just "asdf"
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false  # don't include source code
                    members_order: source  # order methods according to their order of definition in the source code, not alphabetical order
                    heading_level: 4

nav:
    - 'index.md'
    - Tutorials:
          - 'getting_started/Adversarial_Attack.ipynb'
          - 'getting_started/Transfer_Learning.ipynb'
          - 'getting_started/Self-Attention Maps.ipynb'
    - Evaluation:
        - 'comparison.md'
    - Full API:
        - Classification models:
            - 'api/models/classification/alexnet.md'
            - 'api/models/classification/convnext.md'
            - 'api/models/classification/densenet.md'
            - 'api/models/classification/efficientnet.md'
            - 'api/models/classification/efficientnet_v2.md'
            - 'api/models/classification/googlenet.md'
            - 'api/models/classification/mobilenetv2.md'
            - 'api/models/classification/mobilenetv3.md'
            - 'api/models/classification/regnets.md'
            - 'api/models/classification/resnets.md'
            - 'api/models/classification/shufflenetv2.md'
            - 'api/models/classification/squeeze.md'
            - 'api/models/classification/swin.md'
            - 'api/models/classification/swin_v2.md'
            - 'api/models/classification/vgg.md'
            - 'api/models/classification/vit.md'
        - Segmentation models:
            - 'api/models/segmentation/fcn.md'
        - Vision Layers:
            - 'api/layers/conv_norm_act.md'
            - 'api/layers/drop_path.md'
            - 'api/layers/extensions_2d.md'
            - 'api/layers/mlp.md'
            - 'api/layers/patch.md'
            - 'api/layers/squeeze.md'
        - 'api/utils.md'
